# Сервер взаимодействия 1С 8.3
# https://its.1c.ru/db/v8311doc/content/232/hdoc

FROM bellsoft/liberica-openjdk-debian:11
MAINTAINER asda.ru (Andrey Mamaev)

RUN mkdir -p /usr/share/man/man1 && \
	apt-get update && apt-get install -y \
	wget curl sudo

ADD dist /opt/dist

RUN cd /opt/dist && chmod +x 1ce-installer-cli && ./1ce-installer-cli install

RUN apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /opt/dist/*
		
COPY restart.sh /
COPY init_ring.sh /
RUN chmod +x /*.sh

RUN mkdir -p /var/cs/cs_instance && \
	mkdir -p /var/cs/hc_instance && \
	mkdir -p /var/cs/elastic_instance

RUN ./init_ring.sh

#TODO: from shell

ENV PATH=$PATH:/opt/1C/1CE/components/1c-enterprise-ring-0.19.5+12-x86_64

RUN echo $PATH

RUN ring cs instance create --dir /var/cs/cs_instance --owner root 
RUN ring cs --instance cs_instance service create --username root --stopped --java-home $JAVA_HOME
RUN ring hazelcast instance create --dir /var/cs/hc_instance --owner root && \
	ring hazelcast --instance hc_instance service create --username root --stopped --java-home $JAVA_HOME
RUN ring elasticsearch instance create --dir /var/cs/elastic_instance --owner root && \
	ring elasticsearch --instance elastic_instance service create --username root --stopped --java-home $JAVA_HOME

ENV POSTGRES_URL "postgres:5432/cs"
ENV POSTGRES_USER "postgres"
ENV POSTGRES_PASSWORD "postgres"

EXPOSE 9094

CMD ["/restart.sh"]
